version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ppd_tracker_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: laravel_web
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ppd_tracker
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
